### ISSUE TITLE
Mittelwertsatz: Formale und bildliche Erklärung

### ISSUE THREAD

**Issue by kulla** [serlo-org/community-projects#23]
https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Mittelwertsatz#Motivation

**Comment by kulla** [comment]
Und https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks:_Mittelwertsatz#Mittelwertsatz

**Comment by MenujaMS** [comment]
Das Video hierzu wurde schon aufgenommen :) Das Video werde ich noch schneiden und anschließend hochladen.

**Comment by MenujaMS** [comment]
Das Video habe ich auf "MJ Education" veröffentlicht und auf "Mathe für Nicht-Freaks" eingebunden.

**Comment by kulla** [comment]
@MenujaMS Dank dir!
